[versions]
commons-lang3 = "3.20.0"
cxf = "4.2.0"
jakarta-jws-api = "3.0.0"
jakarta-xml-bind = "4.0.5"
jakarta-xml-ws = "4.0.3"
jaxb-basics-runtime = "2.0.12"
jaxb-commons-lang = "2.4"
jaxb-fluent-api = "3.0"
jaxb = "4.0.6"
jaxws = "4.0.3"
jetty = "12.1.6"
junit = "6.0.3"
servlet-api = "6.1.0"
testLogger = "4.0.0"
waena = "0.21.2"
xmlunit = "1.6"

[libraries]
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
cxf-rt-frontend-jaxws = { module = "org.apache.cxf:cxf-rt-frontend-jaxws", version.ref = "cxf" }
cxf-rt-transports-http = { module = "org.apache.cxf:cxf-rt-transports-http", version.ref = "cxf" }
jakarta-jws-api = { module = "jakarta.jws:jakarta.jws-api", version.ref = "jakarta-jws-api" }
jakarta-xml-bind-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jakarta-xml-bind" }
jakarta-xml-ws-api = { module = "jakarta.xml.ws:jakarta.xml.ws-api", version.ref = "jakarta-xml-ws" }
jaxb-basics-runtime = { module = "org.jvnet.jaxb2_commons:jaxb2-basics-runtime", version.ref = "jaxb-basics-runtime" }
jaxb-commons-lang = { module = "org.jvnet.jaxb2_commons:jaxb2-commons-lang", version.ref = "jaxb-commons-lang" }
jaxb-fluent-api = { module = "org.jvnet.jaxb2_commons:jaxb2-fluent-api", version.ref = "jaxb-fluent-api" }
jaxb-impl = { module = "com.sun.xml.bind:jaxb-impl", version.ref = "jaxb" }
jaxb-xjc = { module = "com.sun.xml.bind:jaxb-xjc", version.ref = "jaxb" }
jaxws-rt = { module = "com.sun.xml.ws:jaxws-rt", version.ref = "jaxws" }
jaxws-tools = { module = "com.sun.xml.ws:jaxws-tools", version.ref = "jaxws" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }
servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "servlet-api" }
xmlunit = { module = "xmlunit:xmlunit", version.ref = "xmlunit" }

[plugins]
testLogger = { id = "com.adarshr.test-logger", version.ref = "testLogger" }
waena-published = { id = "com.github.rahulsom.waena.published", version.ref = "waena" }
waena-root = { id = "com.github.rahulsom.waena.root", version.ref = "waena" }
